name: Build Solution and Run Tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Build Solution
        run: dotnet build Restaurant.Identification.slnx

      - name: Test Model
        run: dotnet test Restaurant.Identification.Model.Test/Restaurant.Identification.Model.Test.csproj

      - name: Test Application
        run: dotnet test Restaurant.Identification.Application.Test/Restaurant.Identification.Application.Test.csproj

